import axios from "axios";
import Head from "next/head";
import Homepage from "../components/Homepage";

export default function Home({allStudents, allPrograms}) {
  return (
    <div>
      <Head>
        <title>Khemsafe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div>
        <Homepage allPrograms={allPrograms} allStudents={allStudents}  />
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/students");
  const res2 = await axios.get("http://localhost:3000/api/programs");

  return {
    props: {
      allStudents: res.data,
      allPrograms: res2.data,
    },
  };
};
